{
 "title": "CoronaMq",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{status=\"RUNNING\"}"
    }
   ]
  },
  {
   "title": "Open Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{status=\"NEW\"}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{status=\"FAILED\"}"
    }
   ]
  }
 ]
}